services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5440:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
